trigger: none

variables:
  USERNAME: 'poc@dbmaestro.com'
  PASSWORD: 'VmzU9NIDff1BALGXgsh58XXIg89FH7U5'
  SERVER: 't21-jc'
  AGENT_PATH: '"C:\\Program Files (x86)\\DBmaestro\\DOP Server\\Agent\\DBmaestroAgent.jar"'
  PROJECT_NAME: 'MSSQLPOC2'

stages:
- stage: packaging
  displayName: 'Packaging'
  jobs:
  - job: zip_package_folder
    displayName: 'Zip Package Folder'
    pool:
      name: Local
      demands:
      - agent.name -equals localhostagent
    steps:
      - script: |
          python python-integ-lib\main.py t21-jc 8017 n "DBmaestro Account" poc@dbmaestro.com VmzU9NIDff1BALGXgsh58XXIg89FH7U5 "C:\\Program Files (x86)\\DBmaestro\\DOP Server\\Agent\\DBmaestroAgent.jar" versions MSSQL_P2 RS precheckAllOneByOne
