trigger: none

variables:
  USERNAME: 'poc@dbmaestro.com'
  PASSWORD: 'VmzU9NIDff1BALGXgsh58XXIg89FH7U5'
  SERVER: 't21-jc'
  AGENT_PATH: '"C:\\Program Files (x86)\\DBmaestro\\DOP Server\\Agent\\DBmaestroAgent.jar"'
  PROJECT_NAME: 'MSSQL_P2'

stages:
- stage: rollback
  # condition: always()
  displayName: 'Rollback'
  jobs:
  - job: go
    displayName: 'Go'
    pool:
      name: Local
      demands:
      - agent.name -equals localhostagent
    steps:
      - script: |
          java -jar $(AGENT_PATH) -Rollback -PackageName $(PACKAGE_NAME) -ProjectName $(PROJECT_NAME) -EnvName $(ENV_NAME) -Server $(SERVER) -AuthType DBmaestroAccount -Username $(USERNAME) -Password $(PASSWORD)