trigger: none

variables:
  USERNAME: 'poc@dbmaestro.com'
  PASSWORD: 'VmzU9NIDff1BALGXgsh58XXIg89FH7U5'
  SERVER: 't21-jc'
  AGENT_PATH: '"C:\\Program Files (x86)\\DBmaestro\\DOP Server\\Agent\\DBmaestroAgent.jar"'
  PROJECT_NAME: 'MSSQL_P2'

stages:
- stage: upgradeRS
  # condition: always()
  displayName: 'Upgrade RS'
  jobs:
  - job: dbm_upgrade_rs_cmd
    displayName: 'RS'
    pool:
      name: Local
      demands:
      - agent.name -equals localhostagent
    steps:
      - script: |
          java -jar $(AGENT_PATH) -Upgrade -PackageName $(PACKAGE_NAME) -ProjectName $(PROJECT_NAME) -EnvName RS -Server $(SERVER) -AuthType DBmaestroAccount -Username $(USERNAME) -Password $(PASSWORD)
- stage: upgradeQA
  # condition: always()
  displayName: 'Upgrade QA'
  jobs:
  - job: dbm_upgrade_qa_cmd
    displayName: 'QA'
    pool:
      name: Local
      demands:
      - agent.name -equals localhostagent
    steps:
      - script: |
          java -jar $(AGENT_PATH) -Upgrade -PackageName $(PACKAGE_NAME) -ProjectName $(PROJECT_NAME) -EnvName QA -Server $(SERVER) -AuthType DBmaestroAccount -Username $(USERNAME) -Password $(PASSWORD)          
- stage: upgradeUAT
  # condition: always()
  displayName: 'Upgrade UAT'
  jobs:
  - job: dbm_upgrade_uat1_cmd
    displayName: 'UAT1'
    pool:
      name: Local
      demands:
      - agent.name -equals localhostagent
    steps:
      - script: |
          java -jar $(AGENT_PATH) -Upgrade -PackageName $(PACKAGE_NAME) -ProjectName $(PROJECT_NAME) -EnvName UAT1 -Server $(SERVER) -AuthType DBmaestroAccount -Username $(USERNAME) -Password $(PASSWORD)          
- job: dbm_upgrade_uat2_cmd
    displayName: 'UAT2'
    pool:
      name: Local
      demands:
      - agent.name -equals localhostagent
    steps:
      - script: |
          java -jar $(AGENT_PATH) -Upgrade -PackageName $(PACKAGE_NAME) -ProjectName $(PROJECT_NAME) -EnvName UAT2 -Server $(SERVER) -AuthType DBmaestroAccount -Username $(USERNAME) -Password $(PASSWORD)                    
      